### ISSUE TITLE
Support dartdoc --include option for API doc generation

### ISSUE THREAD

**Issue by chalin** [dart-lang/pub-dev#1216]
A package's pubspec documentation entry could support an `include` entry; e.g.

```yaml
documentation:
  url: optional-url
  include: optional-list-of-libs
```

This is motivated by
- https://github.com/dart-lang/site-webdev/issues/1440
- https://github.com/dart-lang/angular_components/issues/242

cc @kevmoo @kwalrath @nshahan
