### ISSUE TITLE
use "updated health" checks

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2111]
See: https://cloud.google.com/appengine/docs/flexible/custom-runtimes/configuring-your-app-with-app-yaml#health_checks

I propose we add the following to `app|analyzer|dartdoc|search.yaml`
```yaml
liveness_check:
readiness_check:
  app_start_timeout_sec: 600
```

Maybe we can give search longe startup time than the others...
