### ISSUE TITLE
Package dependency flutter is not hosted on pub.dev.

### ISSUE THREAD

**Issue by ledfuse** [dart-lang/pub-dev#2447]
I am trying to publish an update for a Flutter plugin on pub.dev. The same operation would work fine just 2 days ago, but now it will refuse to start.

```
$ flutter pub pub publish
Publishing dvote 0.2.2 to https://pub.dartlang.org:
|-- .gitignore
[...]
|   |-- gateway.dart
|   '-- util
|       '-- content-uri.dart
|-- pubspec.yaml
'-- test
    '-- dvote_test.dart

Looks great! Are you ready to upload your package (y/n)? y
Uploading...
Package dependency flutter is not hosted on pub.dev.
pub finished with exit code 1
```

Is there a known cause for `Package dependency flutter is not hosted on pub.dev `?

Thank you!

**Comment by jonasfj** [comment]
Please post your pubspec, probably you have `dependency: flutter: ...` when you actually want an `sdk` constraint instead..
Example:
https://github.com/flutter/plugins/blob/821c04152f211f132496888c14aa53d8de77dae4/packages/camera/pubspec.yaml#L15-L17

https://github.com/flutter/plugins/blob/821c04152f211f132496888c14aa53d8de77dae4/packages/camera/pubspec.yaml#L28-L30

Does this make sense?

**Comment by ledfuse** [comment]
Thanks for your response @jonasfj 

It's weird, because the `pubspec.yaml` file looks pretty much the same as when it was scaffolded by the CLI:

```yaml
name: dvote
description: Flutter plugin to allow native mobile apps to interact with Vocdoni decentralized votes.
version: 0.2.2
author: DVote Labs <root@dvotelabs.com>
homepage: https://gitlab.com/vocdoni/dvote-flutter
repository: https://gitlab.com/vocdoni/dvote-flutter.git
documentation: https://vocdoni.io/docs

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  web_socket_channel: ^1.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.dvote.dvote
    pluginClass: DvotePlugin

  # more comments below
```

The only difference I can spot from your example is `environment: flutter` but even after adding `flutter: ">=1.5.0 <2.0.0"` the command will still fail:

```
Looks great! Are you ready to upload your package (y/n)? y
Uploading...
Package dependency flutter is not hosted on pub.dev.
pub finished with exit code 1
```
