### ISSUE TITLE
My package is compatible with android/ios/macos but only flagged as "Flutter"

### ISSUE THREAD

**Issue by florent37** [dart-lang/pub-dev#3680]
URL: https://pub.dev/packages/assets_audio_player

My flutter package supports Android/ios/macos (web is on an external repo)

```
flutter:
  plugin:
    platforms:
      android:
        package: com.github.florent37.assets_audio_player
        pluginClass: AssetsAudioPlayerPlugin
        mainClass: AssetsAudioPlayerPlugin
      ios:
        pluginClass: AssetsAudioPlayerPlugin
      macos:
        pluginClass: AssetsAudioPlayerPlugin
```

But when uploaded to pub.dev, it's only flagged as "Flutter"

<img width="461" alt="Capture d’écran 2020-06-02 à 22 19 22" src="https://user-images.githubusercontent.com/5754972/83565698-2154db80-a51f-11ea-96b3-18a64899ba34.png">

# Flutter Doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.19.0-4.0.pre.6, on Mac OS X 10.15.5 19F96, locale fr-FR)
```
