### ISSUE TITLE
Package does not support Flutter platform...Because of import path

### ISSUE THREAD

**Issue by Andrious** [dart-lang/pub-dev#3712]
Recently uploaded package, [mvc_application 5.3.0
](https://pub.dev/packages/mvc_application/versions/5.3.0#-analysis-tab-) to find a number of Analysis suggestions to come up for the first time.

Please, I'm not certain what to do about them.
What is wrong with each 'import path' repeatedly mentioned?

Package does not support Flutter platform android
Package does not support Flutter platform ios
Package does not support Flutter platform linux
Package does not support Flutter platform macos
Package does not support Flutter platform web
Package does not support Flutter platform windows

The following message is of particular concern:

Package not compatible with SDK dart 
because of import path [mvc_application]

Regards,

[andrioussolutions.com](https://pub.dev/publishers/andrioussolutions.com/packages)

**Comment by sigurdm** [comment]
Nothing is wrong with your package.

We are now surfacing how pana came to the conclusion that your package doesn't work on those platforms (and thus did not get those tags).

However path_provider imports a linux only package, and that  breaks down our analysis. This was already discussed here: https://github.com/dart-lang/pub-dev/issues/3680

**Comment by iLnaar** [comment]
I have the same problem:

> Package not compatible with SDK dart
> because of import path [swlabels]

[swlabels](https://pub.dev/packages/swlabels#-analysis-tab-)

**Comment by jhomlala** [comment]
Same here: https://github.com/jhomlala/alice

**Comment by furaiev** [comment]
The same: https://pub.dev/packages/amazon_cognito_identity_dart_2/

**Comment by xclud** [comment]
The same here: https://pub.dev/packages/crop#-analysis-tab-

**Comment by PaoloGi** [comment]
same here: https://pub.dev/packages/nexi_payment#-analysis-tab-

**Comment by imtoori** [comment]
same here: https://pub.dev/packages/stream_chat_flutter/versions/0.2.1-alpha+10#-analysis-tab-

**Comment by JEuler** [comment]
https://pub.dev/packages/instagram_share the same issue.

**Comment by josephvisaac** [comment]
yup. me too:  https://pub.dev/packages/colors_espanol#-analysis-tab-

**Comment by vr19860507** [comment]
https://pub.dev/packages/adt#-analysis-tab-

**Comment by arifai** [comment]
Mee to https://pub.dev/packages/flutter_boxicons#-analysis-tab-

**Comment by RaviKavaiya** [comment]
https://pub.dev/packages/sliding_panel#-analysis-tab-

**Comment by wer-mathurin** [comment]
Same here https://pub.dev/packages/flutter_webrtc/score
This is only a file that contain enum and function use by all the implementation !

**Comment by quick-witted-coder** [comment]
Adding something like this in the package pubspec solves it.
```yaml
flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.auth
        pluginClass: FlutterFirebaseAuthPlugin
      ios:
        pluginClass: FLTFirebaseAuthPlugin
      macos:
        pluginClass: FLTFirebaseAuthPlugin
      web:
        default_package: firebase_auth_web
```
