### ISSUE TITLE
sdk dependencies show up as broken links on package page

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4325]
Context: https://pub.dev/packages/webcrypto

From the `pubspec.yaml`
```yaml
dependencies:
  ffi: ^0.2.0-nullsafety.1
  js: ^0.6.3-nullsafety.3
  meta: ^1.3.0-nullsafety.6
  # Needed for `lib/src/flutter/webcrypto_plugin.dart` which allows boiler-plate
  # in `flutter.plugin.platforms.web` added below.
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
```

![5bLzRvKFJWixyKs](https://user-images.githubusercontent.com/149732/101529695-32c8e580-3991-11eb-84bc-7e579c1d5d19.png)

I expected links for:
 * `flutter_web_plugins`
 * `flutter`
To point to:
 * `https://api.flutter.dev/flutter/package-flutter_web_plugins_flutter_web_plugins/package-flutter_web_plugins_flutter_web_plugins-library.html`
 * `https://api.flutter.dev/`, respectively.

**Or we could simply omit the `sdk: flutter` dependencies form the list of dependency links. I think that's fine.**
