### ISSUE TITLE
[Feature] Exclude supports for certain platform

### ISSUE THREAD

**Issue by Sunbreak** [dart-lang/pub-dev#4602]
https://pub.dev/packages/libusb supports only Windows/macOS/Linux

Could we exclude the `TAG`s of Android/iOS?

<img width="701" alt="Screen Shot 2021-03-12 at 3 49 09 PM" src="https://user-images.githubusercontent.com/7928961/110918474-2c625500-8356-11eb-9c23-8418c755124e.png">

BTW: `libusb` is a Dart package, neither Flutter plugin nor Flutter package. None of it dependency declared something like:

```yaml
flutter:
  plugin:
    platforms:
      android: xxx
      ios: xxx
```

**Comment by isoos** [comment]
@Sunbreak: can you think of any intrinsic property inside the package that we can detect and could suggest us that it supports desktop platforms only?

**Comment by Sunbreak** [comment]
Maybe something like:

```yaml
dart:
  native:
    platforms: [windows, linux, macos]
```
