### ISSUE TITLE
Improve package inheritance when maintainer quits

### ISSUE THREAD

**Issue by diegogarciar** [dart-lang/pub-dev#4757]
Use case

With the migration to null safety we all have struggled asking package maintainers to migrate their code. But what has really been annoying is that there is always a pull request from the community just waiting for the package owner to accept the PR.

I have sent personal emails to those package owners to accept the PRs and even volunteering myself as a collaborator, I succeeded in one. but I cannot just collaborate on all packages myself, we need more volunteers.

The flutter community is growing but the package owner is only one.

Proposal

It would be awesome if we could find different and easier ways to pass on the package once the developer no longer has the interest or time on maintaining it, without the need to create a new package with the same functionality but different name.

If we don't improve this, all pubspec.yaml will look like this:

``` yaml
autocomplete_textfield:
    git: https://github.com/Zeswen/flutter-autocomplete-textfield
smooth_star_rating:
    git: https://github.com/bhavin-concetto/smoothratingbar
 uni_links:
    git:
      url: git@github.com:orevial/uni_links
      ref: null-safety-migration
      path: uni_links
flutter_twilio_voice:
    url: git://github.com/diegogarciar/flutter_twilio_voice.git
facebook_app_events: 
    git: https://github.com/GaspardMerten/flutter_facebook_app_events
flushbar:
    git: https://github.com/prasadsunny1/flushbar
```
These are all actually taken from my pubspec.yaml
