### ISSUE TITLE
Invalid `publish_to` value: `https://pub.dev`.

### ISSUE THREAD

**Issue by RevilionDev** [dart-lang/pub-dev#5493]
I'm trying to update my package but it seems it doesn't work well anymore? A month ago, it was works fine well but now it's not?

I also tried `dart pub publish --dry-run`:

```
Package has 0 warnings.
The server may enforce additional checks.
```

My pubspecs.yaml (I replaced  somemy package data for several reason):

```
name: "MyPackage"
version: "0.1.8"
documentation: "My Documentation Link"
homepage: "MyHomePageLink"
publish_to: "https://pub.dev"
description: "My Description Here"
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  async: ^2.8.2
  http: ^0.13.4
```

I never update or do something with pubspec.yaml except changing it's version
