### ISSUE TITLE
Score message: 'Documentation URL isn't helpful.' is unhelpful :)

### ISSUE THREAD

**Issue by bsutton** [dart-lang/pub-dev#5871]
I'm  trying to clean up my score on pub.dev for https://pub.dev/packages/onepub/versions/1.2.2

I'm getting  a message on the score page that reads:

```
0/10 points: Provide a valid pubspec.yaml
Documentation URL isn't helpful.
```
My documentation URL is: https://docs.onepub.dev

The message gives no clue as to what the problem is and my link goes to the onepub manual which would seem to be appropriate, so I have no idea how to resolve the issue.

**Comment by bsutton** [comment]
PS: after a change to my home page URL I'm getting the same error for my home page URL.

My pubspec.yaml is:
```yaml
name: onepub
version: 1.2.3
homepage: https://onepub.dev
documentation: https://docs.onepub.dev
description: Command line tools for onepub.dev including a replacement pub command.
environment: 
  sdk: '>=2.12.1 <3.0.0'
dependencies: 
  args: 2.3.0
  basic_utils: 3.8.0
  dcli: 1.20.1
  equatable: 2.0.3
  glob: 2.0.1
  http_multi_server: 3.0.1
  json_annotation: 4.1.0
  meta: 1.7.0
  oauth2: 2.0.0
  path: 1.8.1
  pub_semver: 2.1.0
  settings_yaml: 3.4.1
  shelf: 1.2.0
  stack_trace: 1.10.0
  usage: 4.0.2
  validators2: 3.0.0
  yaml: 3.1.0
  analyzer: 2.3.0
  collection: 1.15.0
  source_span: 1.8.1
  http: 0.13.3
  pool: 1.5.0
  frontend_server_client: 2.1.2
  http_parser: 4.0.0
  crypto: 3.0.1
  async: 2.8.2
  typed_data: 1.3.0
  pedantic: 1.11.1
  yaml_edit: 2.0.2
  watcher: 1.0.0
  win32: 2.0.5
  pubspec: ^2.1.0
  cli_util: ^0.3.5
dev_dependencies: 
  lint_hard: ^2.0.0
  test: 1.17.12
executables: 
  onepub: 
  opub: 
platforms: 
  linux: 
  macos: 
  windows: 
false_secrets: 
  - lib/src/pub/validator/leak_detection.dart
```
