### ISSUE TITLE
Code example for GitHub Workflow does not specify a version

### ISSUE THREAD

**Issue by RockerFlower** [dart-lang/pub-dev#6523]
The code example on this page (`pub.dev/packages/{package-name}/admin`) lacks a version specification, causing GitHub Actions to throw an error.

```
name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    uses: dart-lang/setup-dart/.github/workflows/publish.yml
    # with:
    #   working-directory: path/to/package/within/repository
```

<img width="550" alt="スクリーンショット 2023-03-27 10 39 46" src="https://user-images.githubusercontent.com/5019152/227820748-c7d47b1c-a199-4eef-94ea-49b571ac4741.png">
