### ISSUE TITLE
Forbid publishing unknown SDKs

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#6591]
From: https://pub.dev/packages/remote_ui/pubspec

```yaml
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter_sdk: ">=2.0.0 <3.0.0"
```

Let's forbid users from publishing with unknown SDKs.

I'd propose an error message along the lines:
> Package rejected: Unknown SDK 'flutter_sdk', if you are building a custom Dart SDK please reach out to have it allow listed.

Currently, allowed SDKs:
 * `sdk`
 * `dart` (maybe? I don't recall if the Dart SDK still allows this)
 * `flutter`
 * `fuchsia` (maybe?)

It's possible we should scan all packages on pub.dev to make sure we're not forgetting something.
