### ISSUE TITLE
Searching for non-flutter packages gives mainly flutter packages

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#7212]
With the query ["-sdk:flutter"](https://pub.dev/packages?q=-sdk%3Aflutter)
We get this:
![image](https://github.com/dart-lang/pub-dev/assets/8613953/799327a6-0778-43d2-8623-f0f79cf4d540)

Something seems to be broken somewhere

**Comment by isoos** [comment]
Interesting, the first hit has the following tags:
```
"tags": [
      "is:flutter-favorite",
      "publisher:fluttercommunity.dev",
      "platform:android",
      "platform:ios",
      "platform:windows",
      "platform:linux",
      "platform:macos",
      "platform:web",
      "is:plugin",
      "is:null-safe",
      "is:dart3-compatible",
      "license:bsd-3-clause",
      "license:fsf-libre",
      "license:osi-approved"
    ],
```

the platform tags are probably awarded because of the pubspec:

```
flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.share
        pluginClass: SharePlusPlugin
      ios:
        pluginClass: FPPSharePlusPlugin
      linux:
        dartPluginClass: SharePlusLinuxPlugin
      macos:
        pluginClass: SharePlusMacosPlugin
      web:
        pluginClass: SharePlusWebPlugin
        fileName: src/share_plus_web.dart
      windows:
        dartPluginClass: SharePlusWindowsPlugin
        pluginClass: SharePlusWindowsPluginCApi
```

not yet sure why `sdk:flutter` was missing though...
