### ISSUE TITLE
Canonicalize topics using a YAML file

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#7263]
It would be nice if we could merge topics that are effectively the same. For example, some packages are tagged `widget` while others are tagged `widgets`.

I propose that we make a `canonical-topics.yaml` file somewhere in the repository, and the simply map topics from aliases to canonical topic (when parsing the `topics` section in `pubspec.yaml`).

```yaml
# canonical-topics.yaml
topics:
- topic: widget
  # "description" serves as documentation for next time we need to review a PR
  # proposing that we add another alias
  # This can further be used in:
  #  * https://pub.dev/topics
  #  * tooltips when displaying a topic-link on pub.dev
  description: |
    Packages that contain Flutter widgets.
  # "aliases" is a list topics that should be replaced by "widget"
  aliases:
  - widgets
  - flutter-widget
```

@szakarias, @sigurdm, @isoos, thoughts?

### Pull-request to `canonical-topics.yaml`

The file itself should contain a comment explaining that pull-requests to this file are encouraged.
We'll review them as they come in.

Obviously, it'll easily take a week or two from a PR is merged until we make a deployment and the changes takes effect. But this should be acceptable.

Similarly, I don't think we should be concerned about the PR volume.
There are entire security advisory databases managed using PRs, and hopefully it's not every topic that will have aliases -- though I could imagine some people would enjoy writing descriptions for topics :D

### Name of the file `canonical-topics.yaml`

We could call this file something else.
A topic isn't more or less canonical because it's listed in this file.

Package authors shouldn't be preferring to use topics listed in this file.

The purpose of the file is really just to merge topics that mean the exact same thing.

Making up your own topic for your own framework or new thing that you're inventing is still a good thing to do.

Perhaps we should called it `merged-topics.yaml` or even simpler just `topics.yaml`. As we could even allow pull-request that have no other purpose than adding a description for the topic.

Description could be pretty awesome to have on `https://pub.dev/topics` and would also be great to have in tooltips when display a topic on pub.dev.

### Location of `canonical-topics.yaml`

I'm not entirely sure where we should put this file. Ideally somewhere it can live for a long time. This could be `dart-lang/pub/doc`, or we could just put it in `dart-lang/pub-dev/doc` or `dart-lang/pub-dev/config` or ?

### Creating a `dart.dev/go/canonical-topics.yaml`

I'd like to further propose that we make short-link: `dart.dev/go/canonical-topics.yaml`.
This could go directly to the YAML file, or to a documentation page, though we probably don't need to document this. Might it not be fine, if we simply write some comments in the YAML file explaining how it works.

### Transparency for package authors

I don't think we should score packages using non-canonical topics (or aliases) lower in pana.
It's fine to use topics that are not listed in `canonical-topics.yaml`, the purpose of the file is really just to merge topics that are spelled differently.

But package authors might be confused when they see a different topic on the package page, than the one they added in their `pubspec.yaml`.

I propose that when we display a topic on pub.dev, we add a tooltip containing the description and list of aliaes from `canonical-topics.yaml`. Ofcourse we only do this for topics listed in `canonical-topics.yaml`.

### Rewriting search queries

When searching for a topic that is an alias for a canonical topic the search engine should rewrite the search query (possibly redirecting the link or just displaying the new query + showing the correct results).

This ensures that if people make a link to: `https://pub.dev/packages?q=topic:widgets` then it still works. The query is just rewritten to `topic:widget`.

### Cycle detection test

We'll also need a test case that simply ensures no canonical topic is listed as an alias for a different topic. A simple dumb test that can run in CI.
