### ISSUE TITLE
Score dropped from 110 to 80

### ISSUE THREAD

**Issue by quetool** [dart-lang/pub-dev#7848]
Is something happening with the analyzer? No way I have all of these issues in my package https://pub.dev/packages/web3modal_flutter/versions/3.3.0-beta01/score

Score dropped from 110 to 80. Can you help me address this, pointing me towards the proper direction? Thanks!

**Comment by isoos** [comment]
Both the static analysis and the downgrade analysis is failing on the linked prerelease, and the latest stable is also failing static analysis. Do you have a custom `analysis_options.yaml` that ignores files or warnings/errors?

**Comment by quetool** [comment]
> Do you have a custom analysis_options.yaml that ignores files or warnings/errors?

Yes, but since 6 month ago, and I used to have 110 points at least.

```
# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:lints/recommended.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    non_constant_identifier_names: false
    constant_identifier_names: false
    avoid_print: true
    prefer_single_quotes: true
    sort_pub_dependencies: true
    avoid_unnecessary_containers: true
    cancel_subscriptions: true

analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**/*.freezed.dart'
    - '**/*.g.dart'
    - '**/generated_plugin_registrant.dart'
  errors:
    invalid_annotation_target: ignore
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

```
