### ISSUE TITLE
Hold package version during upgrade

### ISSUE THREAD

**Issue by x0apr** [dart-lang/pub-dev#7857]
Is there a way to hold a package version during upgrade? It's not listed in the sub commands.
Something that works like `apt hold.`
I tried specifying the exact package version like `record: 4.4.4 # hold at 4.4.4` but `dart pub upgrade` doesn't seem to take notice.

**Comment by isoos** [comment]
@x0apr: The exact package version should work as you have described. What's your `pubspec.yaml`? 

Also, some further reading can be found here:
https://dart.dev/tools/pub/dependencies

**Comment by x0apr** [comment]
This is how the pubsec.yaml looks.

```
name: name
description: description
publish_to: 'none'
version: 0.1.1+15

environment:
  sdk: '>=3.3.0 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter

  adaptive_theme: ^3.2.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.0.14
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.2.19
  bottom_nav:
    path: packages/bottom_nav
  search_page:
    path: packages/search_page
  http: ^1.1.0
  timezone: ^0.9.2
  flutter_screenutil: ^5.8.4
  audioplayers: ^6.0.0
  file_picker: ^8.0.0+1
  path: ^1.9.0
  icons_plus: ^5.0.0
  record: 4.4.4 # hold at 4.4.4


dev_dependencies:
  #dart run build_runner build
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/


#dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
```
